fix: spotify name
mikejgray/skill-mark2-audio-receiver pull request #16
Opened 2023-11-14 16:48 UTC by mikejgray

# Description
The name of the Raspotify device was not properly taking effect. This was due to a combination of the PHAL plugin not restarting the service as well as the properties in this skill not being set correctly.

# Issues
https://github.com/NeonGeckoCom/skill-mark2-audio-receiver/issues/15

2023-11-14 17:07 UTC, mikejgray commented
Failing test does not appear related to change

2023-11-14 18:13 UTC, NeonDaniel requested changes

2023-11-14 18:13 UTC, NeonDaniel commented on skill_markII_audio_receiver/__init__.py
> +    def initialize(self):
I believe everything here can just be appended to `__init__` to resolve the test failures. As of `ovos-workshop` 0.0.12 init should handle bus init in the `super()` call

2023-11-16 03:04 UTC, NeonDaniel commented on skill_markII_audio_receiver/__init__.py
> +                {"name": self.raspotify_name},
adding context `{"skill_id": self.skill_id}` should resolve the test failures here..

2023-11-16 03:04 UTC, NeonDaniel commented on skill_markII_audio_receiver/__init__.py
> +                {"name": airplay_name},
adding context {"skill_id": self.skill_id} should resolve the test failures here

2023-11-16 20:57 UTC, NeonDaniel requested changes

2023-11-16 20:57 UTC, NeonDaniel commented on skill_markII_audio_receiver/__init__.py
> +                    Message(
`message.forward` should be used here to preserve context (session, skill_id, etc)
```python
message.forward("neon.phal.plugin/audio.receiver.set.raspotify.name", {"name": new_name})
```

2023-11-16 20:57 UTC, NeonDaniel commented on skill_markII_audio_receiver/__init__.py
> +                Message(
same as above, should use `message.forward`

2023-11-16 20:57 UTC, NeonDaniel commented on skill_markII_audio_receiver/__init__.py
> +                Message(
same as above, should use `message.forward`

2023-11-16 21:25 UTC, NeonDaniel approved these changes

2023-11-16 21:26 UTC, merged